In [43]:
import numpy as np
import matplotlib.pyplot as plt
from tueplots import figsizes
from tueplots import axes
from numpy.linalg import cholesky

#plitting specifications
plt.rcParams.update(axes.lines())
plt.rcParams.update({"figure.dpi": 600})
figsize_config = figsizes.aaai2024_half(nrows=2, ncols=1)
plt.rcParams.update(figsize_config)
color_cycler = plt.rcParams['axes.prop_cycle']
colors = color_cycler.by_key()['color']

### Problem

In [ ]:
#define the problem itself
#define IVP -> ODE + IV
def vf(x, t):
    return x*(x-1)

t0 = 0
t1 = 1
x0 = np.array([0.01])
d = x0.shape[0]

### Model

In [ ]:
#prior 
q = 3
prior = GMP_priors.IWP(x0, d, q)

# domain discretization
N = 11 # or vice verca define h -> N = (t1-t0)/h + 1
ts, h = np.linspace(t0, t1, N, retstep=True)
A_h = prior.A(h)
Q_h = prior.Q(h)

# parameters
mu_0 = prior.mu_0
Sigma_0_sqr = cholesky(prior.sigma_0, upper=True)
b_h = prior.b_h
Q_h_sqr = cholesky(Q_h, upper=True)
R_h_sqr = ...
g = ...
jacobian_g = ...
z_sequence = ...


#apply ODE filter
results = kf1_sqr_loop(
    mu_0, Sigma_0_sqr, A_h, b_h, Q_h_sqr, R_h_sqr, g, jacobian_g, z_sequence, N)

In [1]:
import numpy as np
from ode_filters.GMP_priors import _make_iwp_state_matrices, IWP

A, Q = _make_iwp_state_matrices(2)

In [2]:
Q(1)

array([[0.05      , 0.125     , 0.16666667],
       [0.125     , 0.33333333, 0.5       ],
       [0.16666667, 0.5       , 1.        ]])

In [12]:
iwp = IWP(0.2, 2)

In [9]:
iwp.A(2)

array([[1., 0., 2., 0., 2., 0.],
       [0., 1., 0., 2., 0., 2.],
       [0., 0., 1., 0., 2., 0.],
       [0., 0., 0., 1., 0., 2.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [11]:
np.kron(A(2), np.eye(2))

array([[1., 0., 2., 0., 2., 0.],
       [0., 1., 0., 2., 0., 2.],
       [0., 0., 1., 0., 2., 0.],
       [0., 0., 0., 1., 0., 2.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])